FROM node:22-alpine

WORKDIR /app

# Instala dependencias basicas
COPY package*.json ./
COPY packages/utils/package*.json ./packages/utils/
COPY packages/zambdas/package*.json ./packages/zambdas/

RUN npm install --ignore-scripts

# Copia codigo-fonte necessario
COPY packages/utils ./packages/utils
COPY packages/zambdas ./packages/zambdas

WORKDIR /app/packages/zambdas

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production

CMD ["npx", "tsx", "src/local-server/index.ts"]
